#!/bin/bash

if [ -z "$EMAIL" ]; then
    echo "❌ Environment variables are not set!"
    exit 1
fi

cd "$WORK_DIR"*

echo "Setting git config..."
git config --global user.email "$EMAIL" && git config --global user.name "$NAME"
