#!/bin/bash

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "⚠️  Please run this script with: source $0"
    exit 1
fi

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

source "$SCRIPT_DIR/set-up-github"
source "$SCRIPT_DIR/set-aliases"
